/**
 * ============================================================================
 * VeriVote Kenya - Database Type Definitions
 * ============================================================================
 * 
 * This file contains TypeScript types for working with database entities.
 * 
 * WHY SEPARATE TYPES?
 * -------------------
 * 1. Prisma generates types, but they're for database entities only
 * 2. We often need types for:
 *    - API request bodies (CreateVoterInput)
 *    - API responses (PaginatedResponse)
 *    - Partial updates (UpdateVoterInput)
 *    - Statistics and aggregations (VoterStats)
 * 
 * TYPE CATEGORIES:
 * ----------------
 * - Entity types: Direct from Prisma (Voter, Vote, etc.)
 * - Input types: For creating/updating records
 * - Query types: For filtering and pagination
 * - Response types: For API responses
 * - Statistics types: For dashboards and reports
 * 
 * ============================================================================
 */

import type { 
  Voter as PrismaVoter, 
  Vote as PrismaVote, 
  PollingStation as PrismaPollingStation,
  PrintQueue as PrismaPrintQueue,
  VoterStatus,
  VoteStatus,
  PrintStatus
} from '@prisma/client';

// ============================================================================
// RE-EXPORT PRISMA ENUMS
// ============================================================================
// These are generated by Prisma from your schema
// Re-exporting makes importing easier in other files

export { VoterStatus, VoteStatus, PrintStatus };

// ============================================================================
// ENTITY TYPES
// ============================================================================
// These are direct re-exports of Prisma-generated types
// They represent a complete database row

/** 
 * A registered voter
 * Includes all columns from the voters table
 */
export type Voter = PrismaVoter;

/**
 * A cast vote
 * Includes all columns from the votes table
 */
export type Vote = PrismaVote;

/**
 * A polling station
 * Includes all columns from the polling_stations table
 */
export type PollingStation = PrismaPollingStation;

/**
 * A print queue item
 * Includes all columns from the print_queue table
 */
export type PrintQueue = PrismaPrintQueue;

// ============================================================================
// INPUT TYPES - For Creating Records
// ============================================================================
// These types define what data is REQUIRED when creating new records
// They omit auto-generated fields (id, createdAt, etc.)

/**
 * Data required to create a new voter
 * Used by: POST /api/voters/register
 */
export interface CreateVoterInput {
  nationalId: string;           // Required: Kenya national ID
  pollingStationId?: string;    // Optional: Assigned polling station
}

/**
 * Extended voter registration with PIN data
 * Used internally after PIN generation
 */
export interface RegisterVoterInput extends CreateVoterInput {
  pin: string;          // Raw PIN (will be hashed before storage)
  distressPin: string;  // Raw distress PIN (will be hashed)
}

/**
 * Data for creating a new vote
 * Used by: POST /api/votes/cast
 */
export interface CreateVoteInput {
  encryptedVoteHash: string;    // SHA-256 hash of encrypted vote
  encryptedVoteData?: string;   // Full encrypted vote (optional)
  serialNumber: string;         // Unique receipt number
  zkpProof?: string;            // Zero-knowledge proof
  pollingStationId: string;     // Where vote was cast
  previousVoteId?: string;      // If this is a revote
}

/**
 * Data for creating a polling station
 * Used by: Admin panel
 */
export interface CreatePollingStationInput {
  code: string;           // Unique station code (e.g., "NAI-WL-001")
  name: string;           // Station name
  county: string;         // Kenya county
  constituency: string;   // Electoral constituency
  ward: string;           // Ward name
  latitude?: number;      // GPS latitude
  longitude?: number;     // GPS longitude
  address?: string;       // Physical address
  registeredVoters?: number; // Expected voter count
  deviceCount?: number;   // Number of voting devices
  printerCount?: number;  // Number of printers
}

/**
 * Data for adding a vote to print queue
 * Used by: Print system
 */
export interface CreatePrintQueueInput {
  voteId: string;           // Vote to print
  pollingStationId: string; // Where to print
  priority?: number;        // Print priority (higher = more urgent)
}

// ============================================================================
// INPUT TYPES - For Updating Records
// ============================================================================
// All fields are optional (partial updates)

/**
 * Fields that can be updated on a voter
 */
export interface UpdateVoterInput {
  sbtAddress?: string;        // Blockchain wallet address
  sbtTokenId?: string;        // SBT token ID
  sbtMintedAt?: Date;         // When SBT was minted
  pinHash?: string;           // Updated PIN hash
  distressPinHash?: string;   // Updated distress PIN hash
  status?: VoterStatus;       // New status
  voteCount?: number;         // Updated vote count
  lastVotedAt?: Date;         // Last vote timestamp
  pollingStationId?: string;  // Reassign to different station
}

/**
 * Fields that can be updated on a vote
 */
export interface UpdateVoteInput {
  blockchainTxHash?: string;  // Transaction hash after blockchain recording
  blockNumber?: bigint;       // Block number
  confirmedAt?: Date;         // Confirmation timestamp
  status?: VoteStatus;        // New status
}

/**
 * Fields that can be updated on a polling station
 */
export interface UpdatePollingStationInput {
  name?: string;
  latitude?: number;
  longitude?: number;
  address?: string;
  registeredVoters?: number;
  isActive?: boolean;
  openingTime?: Date;
  closingTime?: Date;
  deviceCount?: number;
  printerCount?: number;
}

/**
 * Fields that can be updated on a print queue item
 */
export interface UpdatePrintQueueInput {
  status?: PrintStatus;
  printerId?: string;
  printedAt?: Date;
  printAttempts?: number;
  lastError?: string;
  ballotNumber?: string;
  qrCodeData?: string;
}

// ============================================================================
// QUERY TYPES - For Filtering and Pagination
// ============================================================================

/**
 * Common pagination parameters
 * Used across all list endpoints
 */
export interface PaginationParams {
  page?: number;    // Page number (1-based)
  limit?: number;   // Items per page
}

/**
 * Query parameters for listing voters
 * Used by: GET /api/voters
 */
export interface VoterQueryParams extends PaginationParams {
  status?: VoterStatus;       // Filter by status
  pollingStationId?: string;  // Filter by station
  hasSbt?: boolean;           // Filter by SBT presence
  hasVoted?: boolean;         // Filter by voting status
}

/**
 * Query parameters for listing votes
 * Used by: GET /api/votes
 */
export interface VoteQueryParams extends PaginationParams {
  status?: VoteStatus;        // Filter by status
  pollingStationId?: string;  // Filter by station
  fromDate?: Date;            // Filter by date range
  toDate?: Date;
  confirmedOnly?: boolean;    // Only blockchain-confirmed
}

/**
 * Query parameters for listing polling stations
 * Used by: GET /api/polling-stations
 */
export interface PollingStationQueryParams extends PaginationParams {
  county?: string;            // Filter by county
  constituency?: string;      // Filter by constituency
  ward?: string;              // Filter by ward
  isActive?: boolean;         // Filter by active status
}

/**
 * Query parameters for listing print queue
 * Used by: GET /api/print-queue
 */
export interface PrintQueueQueryParams extends PaginationParams {
  status?: PrintStatus;       // Filter by status
  pollingStationId?: string;  // Filter by station
  printerId?: string;         // Filter by printer
}

// ============================================================================
// RESPONSE TYPES
// ============================================================================

/**
 * Standard paginated response format
 * All list endpoints return this structure
 * 
 * Example:
 * {
 *   data: [...],
 *   pagination: {
 *     total: 100,
 *     page: 1,
 *     limit: 20,
 *     totalPages: 5,
 *     hasNext: true,
 *     hasPrev: false
 *   }
 * }
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    total: number;      // Total items in database
    page: number;       // Current page
    limit: number;      // Items per page
    totalPages: number; // Total pages available
    hasNext: boolean;   // Is there a next page?
    hasPrev: boolean;   // Is there a previous page?
  };
}

// ============================================================================
// STATISTICS TYPES - For Dashboards
// ============================================================================

/**
 * Voter statistics for admin dashboard
 */
export interface VoterStats {
  total: number;              // Total registered voters
  byStatus: {
    registered: number;       // Voters who haven't voted
    voted: number;            // Voters who voted once
    revoted: number;          // Voters who changed their vote
    distressFlagged: number;  // Voters flagged for review
    suspended: number;        // Suspended accounts
  };
  withSbt: number;            // Voters with SBT assigned
  turnoutPercentage: number;  // Percentage who have voted
}

/**
 * Vote statistics for admin dashboard
 */
export interface VoteStats {
  total: number;
  byStatus: {
    pending: number;          // Awaiting blockchain confirmation
    confirmed: number;        // Confirmed on blockchain
    superseded: number;       // Replaced by revotes
    invalidated: number;      // Invalidated votes
  };
  confirmedOnBlockchain: number;
  averageConfirmationTime?: number; // Average time to confirm (seconds)
}

/**
 * Polling station statistics
 */
export interface PollingStationStats {
  totalStations: number;
  activeStations: number;
  totalRegisteredVoters: number;
  totalVotesCast: number;
  overallTurnout: number;     // Percentage
  byCounty: {
    county: string;
    stations: number;
    voters: number;
    votes: number;
    turnout: number;
  }[];
}

/**
 * Print queue statistics
 */
export interface PrintQueueStats {
  total: number;
  byStatus: {
    pending: number;
    printing: number;
    printed: number;
    failed: number;
    cancelled: number;
  };
  averagePrintTime?: number;  // Average time to print (seconds)
  failureRate: number;        // Percentage of failed prints
}

// ============================================================================
// COMPOSITE TYPES - Entities with Relations
// ============================================================================

/**
 * Voter with their polling station data included
 * Used when you need station details without a separate query
 */
export interface VoterWithStation extends Voter {
  pollingStation: PollingStation | null;
}

/**
 * Vote with polling station data included
 */
export interface VoteWithStation extends Vote {
  pollingStation: PollingStation;
}

/**
 * Vote with print status included
 */
export interface VoteWithPrintStatus extends Vote {
  pollingStation: PollingStation;
  printQueue: PrintQueue | null;
}

/**
 * Print queue item with full related data
 */
export interface PrintQueueWithDetails extends PrintQueue {
  vote: Vote;
  pollingStation: PollingStation;
}
