# pnpm Workspace Configuration
# This tells pnpm that this is a monorepo with multiple packages

packages:
  # Backend API
  - 'backend'
  
  # Frontend web application (Next.js)
  - 'frontend'
  
  # Blockchain smart contracts
  - 'smart-contracts'
