-- Add new IEBC staff role values to the StaffRole enum
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'CHAIRPERSON';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'COMMISSION_SECRETARY';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'DEPUTY_COMMISSION_SECRETARY';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'DIRECTOR';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'REGIONAL_COORDINATOR';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'DEPUTY_PRESIDING_OFFICER';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'POLLING_CLERK';
ALTER TYPE "StaffRole" ADD VALUE IF NOT EXISTS 'SECURITY_OFFICER';

-- Add department column for Director/Manager functional area
ALTER TABLE "iebc_staff" ADD COLUMN IF NOT EXISTS "department" VARCHAR(100);
