/**
 * VeriVote Kenya — Unified Election Ceremony Service
 *
 * Orchestrates the full election ceremony in one call:
 *   Phase 1 — Re-encryption Mixnet:  anonymises vote ordering via 3-node
 *              Jakobsson-Juels re-encryption + Fisher-Yates shuffle.
 *   Phase 2 — Threshold Homomorphic Tally: aggregates per-candidate
 *              exponential ElGamal ciphertexts, collects all 3 commissioner
 *              partial decryptions, runs BSGS to recover vote counts.
 *
 * The phases are intentionally sequential: the mixnet runs first so that
 * tallying operates on the anonymised batch.
 *
 * Sovereignty: all operations on-premise. Zero foreign API calls.
 */

import { createHash } from 'crypto';
import { v4 as uuid } from 'uuid';
import { runMixnet, type MixnetResult } from './mixnet.service.js';
import {
  startCeremony,
  submitShare,
  finalizeCeremony,
  resetCeremony,
  getCeremonyState,
  type HomomorphicResult,
  COMMISSIONER_IDS,
} from './homomorphic.service.js';
import { logger } from '../lib/logger.js';

// Re-export so routes only need to import from this module
export type { HomomorphicResult };

// ── Result types ──────────────────────────────────────────────────────────────

export interface MixnetSummary {
  ceremonyId: string;
  inputVoteCount: number;
  outputVoteCount: number;
  finalCommitment: string;
  durationMs: number;
  nodes: MixnetResult['nodes'];
  productionNote: string;
}

export interface ElectionCeremonyResult {
  ceremonySummaryId: string;
  startedAt: string;
  completedAt: string;
  totalDurationMs: number;
  mixnet: MixnetSummary;
  tally: HomomorphicResult;
  /** SHA-256(mixnet.finalCommitment | tally.finalHash) — ties both phases together. */
  integrityHash: string;
  sovereigntyNote: string;
}

// ── In-memory cache ───────────────────────────────────────────────────────────

let _lastResult: ElectionCeremonyResult | null = null;

// ── Ceremony orchestration ────────────────────────────────────────────────────

export async function runElectionCeremony(electionId?: string): Promise<ElectionCeremonyResult> {
  const t0 = Date.now();
  const startedAt = new Date().toISOString();

  logger.info('Unified election ceremony started', { electionId: electionId ?? 'legacy-all' });

  // ── Phase 1: Re-encryption Mixnet ─────────────────────────────────────────
  logger.info('Election ceremony — Phase 1: re-encryption mixnet');
  const mixnetResult = await runMixnet(electionId);

  // ── Phase 2: Threshold Homomorphic Tally ──────────────────────────────────
  logger.info('Election ceremony — Phase 2: threshold homomorphic tally');

  // Clear any stale ceremony state from a previous run
  resetCeremony();
  await startCeremony(electionId);

  // Auto-submit all 3 commissioner SSS shares using the shares generated by startCeremony
  const state = getCeremonyState();
  if (!state) throw new Error('Ceremony state missing after startCeremony');
  for (let i = 0; i < COMMISSIONER_IDS.length; i++) {
    submitShare(COMMISSIONER_IDS[i], state.sssShares[i].hex);
  }

  const tallyResult = finalizeCeremony();

  // ── Build combined result ──────────────────────────────────────────────────
  const completedAt = new Date().toISOString();
  const totalDurationMs = Date.now() - t0;

  const integrityHash = createHash('sha256')
    .update(`${mixnetResult.finalCommitment}|${tallyResult.finalHash}`)
    .digest('hex');

  const result: ElectionCeremonyResult = {
    ceremonySummaryId: uuid(),
    startedAt,
    completedAt,
    totalDurationMs,
    mixnet: {
      ceremonyId:      mixnetResult.ceremonyId,
      inputVoteCount:  mixnetResult.inputVoteCount,
      outputVoteCount: mixnetResult.outputVoteCount,
      finalCommitment: mixnetResult.finalCommitment,
      durationMs:      mixnetResult.durationMs,
      nodes:           mixnetResult.nodes,
      productionNote:  mixnetResult.productionNote,
    },
    tally: tallyResult,
    integrityHash,
    sovereigntyNote:
      'All cryptographic operations (re-encryption mixnet + threshold homomorphic tally) ' +
      'performed on-premise. No individual vote decrypted. Zero foreign API calls.',
  };

  _lastResult = result;

  logger.info('Unified election ceremony completed', {
    ceremonySummaryId: result.ceremonySummaryId,
    integrityHashPrefix: integrityHash.slice(0, 16),
    totalDurationMs,
  });

  return result;
}

export function getLastElectionResult(): ElectionCeremonyResult | null {
  return _lastResult;
}
