import { Router, type Request, type Response } from 'express';
import { z } from 'zod';
import { voteService } from '../services/vote.service.js';
import { ServiceError } from '../services/voter.service.js';
import { requireAuth, voteRateLimiter, receiptRateLimiter } from '../middleware/index.js';
import type { AuthenticatedRequest } from '../types/auth.types.js';

const router: Router = Router();

const castVoteSchema = z.object({
  selections: z.record(z.string(), z.string()).refine(
    (obj) => Object.keys(obj).length > 0,
    { message: 'At least one selection is required' }
  ),
  pollingStationId: z.string().uuid('Invalid polling station ID').optional(),
  pin:              z.string().regex(/^\d{4}$/, 'PIN must be exactly 4 digits').optional(),
  electionId:       z.string().uuid('Invalid election ID').optional(),
});

// POST /api/votes/cast
router.post('/cast', requireAuth, voteRateLimiter, async (req: Request, res: Response) => {
  try {
    const parsed = castVoteSchema.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({
        success: false,
        error: parsed.error.errors.map(e => e.message).join(', '),
      });
      return;
    }

    const authReq = req as AuthenticatedRequest;
    const result = await voteService.castVote(authReq.voter, parsed.data);

    res.status(201).json({
      success: true,
      data: result,
    });
  } catch (error) {
    if (error instanceof ServiceError) {
      res.status(error.statusCode).json({ success: false, error: error.message });
      return;
    }
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Vote casting failed',
    });
  }
});

// GET /api/votes/verify/:serial  (public — no requireAuth)
router.get('/verify/:serial', receiptRateLimiter, async (req: Request, res: Response) => {
  try {
    const { serial } = req.params;

    // Accept both serial formats:
    //   16 hex chars — generated by vote.service.ts (e.g. A3B2C1D4E5F60718)
    //   VV-{8 base36}-{8 hex} — generated by seed.ts  (e.g. VV-MMT3M8FY-A953545D)
    const validSerial = /^[0-9A-F]{16}$/i.test(serial) ||
                        /^VV-[0-9A-Z]{8}-[0-9A-F]{8}$/i.test(serial);
    if (!validSerial) {
      res.status(400).json({
        success: false,
        error: 'Invalid serial number format.',
      });
      return;
    }

    const result = await voteService.verifyVote(serial);

    if (result.message === 'not_found') {
      res.status(404).json({ success: false, error: 'Vote not found' });
      return;
    }

    res.status(200).json({ success: true, data: result });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Verification failed',
    });
  }
});

export default router;
